export { default as usePostRegister } from "./usePostRegister";
export { default as usePostLogin } from "./usePostLogin";
export { default as useGetUserDetails } from "./useGetUserDetails";
export { default as usePostLogout } from "./usePostLogout";
export { default as useGetPlaceLocation } from "./useGetPlaceLocation";
export { default as usePostNewMap } from "./usePostNewMap";
export { default as useGetMapList } from "./useGetMapList";
export { default as useGetMapDetail } from "./useGetMapDetail";
export { default as usePostGoogleLogin } from "./usePostGoogleLogin";
